---
title: "anova"
author: "Jerome"
date: "1/10/2021"
output: html_document
---

```{r}
library(MASS)
library(ggplot2)
data(Cushings)
data(genotype)
```



# http://www.sthda.com/english/articles/31-principal-component-methods-in-r-practical-guide/118-principal-component-analysis-in-r-prcomp-vs-princomp/
```{r}
head(Cushings)
```
```{r}
ggplot(Cushings, aes(x = Type, y = Pregnanetriol)) + geom_boxplot()
ggplot(Cushings, aes(x = Type, y = Tetrahydrocortisone)) + geom_boxplot()

```

```{r}
ggplot(Cushings, aes(x = Type, y = Pregnanetriol)) + geom_point()

```

```{r}
ggplot(Cushings, aes(x = Type, y = Pregnanetriol)) + geom_line()

```
```{r}
mod_p = aov(Pregnanetriol ~ Type, data = Cushings)
summary(mod_p)
```

```{r}
mod_t = aov(Tetrahydrocortisone ~ Type, data = Cushings)
summary(mod_t)
```


## two-way ANOVA
```{r}
head(genotype)
```

```{r}
mod_g = aov(Wt ~ Litter + Mother + Litter*Mother, data = genotype)
summary(mod_g)
```

# chisq test 

```{r}
chisq.test(x = c(24, 16), p = c(0.7, 0.3))
chisq.test(x = c(13, 11, 16), p = c(0.5, 0.2, 0.3))
```

```{r}
data(birthwt)
head(birthwt)
birthwt.tab <- table(birthwt$smoke, birthwt$low)
```

```{r}
chisq.test(birthwt.tab, correct = FALSE)
```

```{r}
chisq.test(birthwt.tab, correct = TRUE)

```


# 
```{r}
# plot the distribution 
plot(0:12, dbinom(0:12, size = 100, prob = 0.05))
```
```{r}
sum(dbinom(0:12, size = 100, prob = 0.05))
```

# by hand 
```{r}
data(PlantGrowth)
str(PlantGrowth)
head(PlantGrowth)
```



```{r}
library(dplyr)

mean_grand =  mean(PlantGrowth$weight)
group_mean = PlantGrowth %>% 
    group_by(group) %>%
    summarise(avg = mean(weight), n = n(), .group = 'keep')

joint_table = PlantGrowth %>%
    left_join(group_mean, by = c('group'))
TSS = sum((PlantGrowth$weight - mean_grand)^2)
GSS = sum((group_mean$avg - mean_grand)^2*group_mean$n)
ESS = sum((joint_table$weight - joint_table$avg)^2)
DF_G = length(unique(PlantGrowth$group)) - 1
DF_E = nrow(PlantGrowth) - length(unique(PlantGrowth$group))
f_stat = (GSS/DF_G)/(ESS/DF_E)
p_val = pf(f_stat, df1 = DF_G, df2 = DF_E, lower.tail = F)
f_stat
p_val

```


```{r}
mod_anova <- aov(weight ~ group, data = PlantGrowth)
summary(mod_anova)
```

# contrast 
```{r}
alpha = 0.95
contrast_vec = c(1, -1, 0)
w_y = t(group_mean$avg) %*% contrast_vec 
t_val = qt(0.025, df = DF_E)
val = sqrt(ESS/DF_E)*sqrt(sum(contrast_vec^2/group_mean$n))
ci_l = w_y - t_val * val
ci_u = w_y + t_val * val
ci_l
ci_u
t_val_test = (w_y - 0)/val 
p_val = 2*pt(t_val_test, df = DF_E, lower.tail = F)
t_val_test
cat("INFO: p val")
p_val
```

# f test 
```{r}
ssw = w_y^2 / sum(contrast_vec^2/group_mean$n)
msw = ssw
mse = ESS/DF_E
f_val_test = msw/mse
p_val = pf(f_val_test, df1 = 1, df2 = DF_E, lower.tail = F)
f_val_test
p_val
```

```{r}
#contrasts(PlantGrowth$group) = contrast_vec

# tell R which groups to compare
c1 <- c(1, -.5, -.5) # 1
c2 <- c(-.5, 1, -.5) # 2
c3 <- c(-.1, 0, 1) # 3
c4 <- c(0,-1,1)

# combined the above 3 lines into a matrix
mat <- cbind(c1,c2,c3, c4)

# tell R that the matrix gives the contrasts you want
contrasts(PlantGrowth$group) <- mat

#contrast_list = list(S1vsS2andS3 = contrast_vec)
mod_anova <- aov(weight ~ group, data = PlantGrowth, contrasts = list(group = mat))
summary.aov(mod_anova, split = list(group = list("v1" = 1, "v2" = 2, "v3" = 3)))
```

# lsmeans
```{r}
mod_anova <- aov(weight ~ group, data = PlantGrowth)
pairs(lsmeans(mod_anova, ~ group))
```


# 
```{r}
E_opt1 = ((20^3 - 40) * 2 + (20^3 - 20) * 2 + 2 * 60)/20^5
E_opt1
```


# distribution 
```{r}

```


#
```{r}
feb_list <- list()

febonacci <- function(n) {
    
    if (n == 0) {
        feb_list[n] <<- 0
        return(0)
    } else if (n == 1 | n == 2) {
        feb_list[n] <<- 1
        return(1)
    } else {
        if (n %in% names(feb_list)) {
            return(feb_list[n])
        } else {
            num <- febonacci(n - 2) + febonacci(n - 1)
            feb_list[n] <<- num
            return(num)
        }
        
    }
    
}

febonacci_iter <- function(n) {
    pre_val = 0 
    cur_val = 1
    for (i in 1:(n - 1)) {
        tmp_val = pre_val + cur_val
        pre_val = cur_val
        cur_val = tmp_val
        
    }
    return(tmp_val)
}
    

for (i in 1:200) {
    print(i)
    temp <- febonacci(i)
}
p_k_head <- function(k, n) {
    sum_val <- 0
    for (i in 1:k) {
        sum_val <- sum_val + febonacci_iter(n + 2 - i)
    }
    print(sum_val)
    return(2^(log2(sum_val) - 100))
}
E_opt2 = 
```


```{r}
n_sim = 100000
sim_mtx = matrix(0, n_sim, 100)
for (i in 1:n_sim) {
    sim_mtx[i, ]  = rbinom(100, size = 1, 0.05)
    
}

count_vec = rep(0, n_sim)
for (i in 1:n_sim) {
    sum_val = 0
    for (j in 2:100) {
        if (sim_mtx[i, j - 1] == 1 & sim_mtx[i, j] == 1) {
            sum_val = sum_val + 1
        }
    }
    count_vec[i] = sum_val
}
```

# sample size calculation 

```{r}
sample_size <- function(baseline, dmin) {
    p_bar <- baseline + dmin/2
    se <- sqrt(p_bar*(1-p_bar))
    return(((qnorm(0.975)*se + qnorm(0.8) * se)/(dmin) *sqrt(2))^2)

}

((qnorm(0.975)* sqrt(0.205*0.795) + qnorm(0.8) * sqrt(0.205*0.795))/(0.01) *sqrt(2))^2
```

```{r}
n_sim = 500000
ct = 0
for (i in 1:n_sim) {
    sample_30 <- sample(1:50, 30)
    j = 1
    while (j < 30) {
        test_sam = sample_30[j:(j+2)]
        j = j + 3
        if (sum(test_sam) == 6) { ct = ct + 1}
    }
    
}

```

# pca
```{r}
library("factoextra")
```

```{r}
data(decathlon2)
decathlon2.active <- decathlon2[1:23, 1:10]
head(decathlon2.active[, 1:6])
```

```{r}
res.pca <- prcomp(decathlon2.active, scale = FALSE)
res.pca_scaled <- prcomp(decathlon2.active, scale = TRUE)

res.pca_2 <- princomp(x, cor = FALSE, scores = TRUE)
mtx <- decathlon2.active
mtx_std <- apply(mtx, 2, scale)
mtx_center <- apply(mtx, 2, function(x) x-mean(x))
test_cor_mtx <- t(mtx_std) %*% mtx_std/(nrow(mtx_std) - 1)
test_cov_mtx <- t(mtx_center) %*% mtx_center/(nrow(mtx_std) - 1)

cov_mtx <- cov(as.matrix(decathlon2.active))
cor_mtx <- cor(as.matrix(decathlon2.active))
eigen_res <- eigen(x = t(as.matrix(decathlon2.active))%*%as.matrix(decathlon2.active)/(nrow(decathlon2.active) - 1))
```

```{r}
res_pca <- as.matrix(decathlon2.active) %*% eigen_res$vectors
norm <- function(vector) {
    sum_tmp <- sqrt(sum(vector^2))
    return(vector/sum_tmp)
}

res_pca_updated <- apply(res_pca, 2, function(x) norm(x))

```

# by hand without scale 
```{r}
Eigenvalues <- eigen(cov(as.matrix(mtx_center)))$values
Eigenvectors <- eigen(cov(as.matrix(mtx_center)))$vectors
PCs <-   as.matrix(mtx_center) %*% Eigenvectors



```

# by hand scaling
```{r}
Eigenvalues <- eigen(cov(as.matrix(mtx_std)))$values
Eigenvectors <- eigen(cov(as.matrix(mtx_std)))$vectors
PCs <-  as.matrix(mtx_std) %*% Eigenvectors


```


# variance explained 
```{r}

fviz_eig(res.pca)
#res.pca$
```
```{r}
head(res.pca$x)
```

```{r}
Eigenvalues <- eigen(cov(as.matrix(mtx_center)))$values
Eigenvectors <- eigen(cov(as.matrix(mtx_center)))$vectors
PCs <-   as.matrix(mtx_center) %*% Eigenvectors
Eigenvalues/sum(Eigenvalues) * 100
```



# by hand 
```{r}

```

