---
title: "naive_bayes"
author: "Jerome"
date: "11/22/2020"
output: html_document
---

```{r}
input_df <- data.frame(x = 1:10, y = c(rep(0, 5), rep(1, 5)))

#p_y | p_x = (p_x | p_y) * p_y / p_x
#p_y = 1 | p_x = (p_x | p_y = 1) * p_y = 1 / p_x
#p_y = 0 | p_x = (p_x | p_y = 0) * p_y = 0 / p_x


p_y_1 = sum(input_df$y == 1)
p_y_0 = sum(input_df$y == 0)

sample_y1 = input_df[input_df$y == 1, ]
sample_y2 = input_df[input_df$y == 0, ]



mean_x_given_y1 = mean(sample_y1$x)
mean_x_given_y2 = mean(sample_y2$x)

sd_x_given_y1 = sd(sample_y1$x)
sd_x_given_y2 = sd(sample_y2$x)

x = 7

prob_y1 = dnorm(x, mean = mean_x_given_y1, sd  = sd_x_given_y1)
prob_y2 = dnorm(x, mean = mean_x_given_y2, sd  = sd_x_given_y2)

p_y1 = (nrow(sample_y1)/nrow(input_df))
p_y2 = (nrow(sample_y2)/nrow(input_df))

prob = prob_y1 * p_y1 / (prob_y1 * p_y1 + prob_y2 * p_y2)
prob





```

# power nad sample size

```{r}
# sample_size calculation 
p_0 = 0.082
p_a = 0.2
#var_0 = p0 * (1- p_0) /n
#var_a = pa * (1- p_a) /n
alpha = 0.01
beta = 0.05

z_a = qnorm(1- alpha, lower.tail = T)
z_b = qnorm(1 - beta, lower.tail = T)

#((p_a) - (p_0 + z_a * sqrt(var_0)) )/ sqrt(var_a) = z_b

#p_a - p_0 = z_a * sqrt(var_0)) + z_b * sqrt(var_a))
#p_a - p_0 = z_a * sqrt(p_0 * (1- p_0) /n)) + z_b * sqrt(p_a * (1- p_a) /n))
#p_a - p_0 = z_a * sqrt(p_0 * (1- p_0) /n)) + z_b * sqrt(p_a * (1- p_a) /n))
#sqrt(n) = (z_a * sqrt(p0 * (1- p_0)) + z_b * sqrt(p_a * (1- p_a)))/(p_a - p_0)
n = ((z_a * sqrt(p_0 * (1- p_0)) + z_b * sqrt(p_a * (1- p_a)))/(p_a - p_0))^2
```


# multinormal distribution
```{r}
library(MASS)
Sigma <- matrix(c(10,3,3,2),2,2)
Sigma
var(mvrnorm(n = 1000, rep(0, 2), Sigma))
var(mvrnorm(n = 1000, rep(0, 2), Sigma, empirical = TRUE))


M <- ncol(genotype) 
  P <- tissue_num
  Bsim <- matrix(rep(0, M*P), nrow = M, ncol = P)
  Bsim[,1] <- rnorm(M) # simulate effect sizes of SNPs in the first tissue and take these directions as standard. 
  #ind_pos <- which(Bsim[,1] >= 0)
  #ind_neg <- which(Bsim[,1] < 0) 
  for (i in 1:length(causal_idx)) {
    Bsim[causal_idx[i], 2:P] <- rnorm(P - 1, mean = Bsim[causal_idx[i], 1])
  }


```

## p
```{r}
n_exp = 50000 + 5979
n_con = 50000 + 6021
x_exp = 374 + 2500
x_con = 302 + 2500
p_exp = x_exp/n_exp
p_con = x_con/n_con
p_pool = (x_exp + x_con)/(n_exp + n_con)
se_pool = sqrt(p_pool * (1-p_pool) * (1/n_con + 1/n_exp))
se_pool


```

```{r}
2 * (1 - pnorm((6.3 - 5.1)/0.42))

```
 
```{r}
2 * (1 - pnorm((x_exp/n_exp - x_con/n_con )/se_pool))
```

# ab tesing 

```{r}
p = 0.20625
sqrt(p*(1-p)/400)
p = 0.53
sqrt(p*(1-p)/(660/8))
p = 0.1093125
sqrt(p*(1-p)/400)

```

5000 * 0.20625

```{r}

#mean_0, mean_a
alpha = 0.05
beta = 0.2

# sample_size calculation 
p_0 = 0.20625
p_a = p_0 - 0.01
#var_0 = p0 * (1- p_0) /n
#var_a = pa * (1- p_a) /n
alpha = 0.05
beta = 0.2

z_a = qnorm(1- alpha, lower.tail = T)
z_b = qnorm(1 - beta, lower.tail = T)

#((p_a) - (p_0 + z_a * sqrt(var_0)) )/ sqrt(var_a) = z_b

#p_a - p_0 = z_a * sqrt(var_0)) + z_b * sqrt(var_a))
#p_a - p_0 = z_a * sqrt(p_0 * (1- p_0) /n)) + z_b * sqrt(p_a * (1- p_a) /n))
#p_a - p_0 = z_a * sqrt(p_0 * (1- p_0) /n)) + z_b * sqrt(p_a * (1- p_a) /n))
#sqrt(n) = (z_a * sqrt(p0 * (1- p_0)) + z_b * sqrt(p_a * (1- p_a)))/(p_a - p_0)
n = ((z_a * sqrt(p_0 * (1- p_0)) + z_b * sqrt(p_a * (1- p_a)))/(p_a - p_0))^2
n
```

```{r}
# sample_size calculation 
p_0 = 0.20625
p_a = p_0 - 0.01
#var_0 = p0 * (1- p_0) /n
#var_a = pa * (1- p_a) /n
alpha = 0.05
beta = 0.2

z_a = qnorm(1- alpha, lower.tail = T)
z_b = qnorm(1 - beta, lower.tail = T)

#((p_a) - (p_0 + z_a * sqrt(var_0)) )/ sqrt(var_a) = z_b

#p_a - p_0 = z_a * sqrt(var_0)) + z_b * sqrt(var_a))
#p_a - p_0 = z_a * sqrt(p_0 * (1- p_0) /n)) + z_b * sqrt(p_a * (1- p_a) /n))
#p_a - p_0 = z_a * sqrt(p_0 * (1- p_0) /n)) + z_b * sqrt(p_a * (1- p_a) /n))
#sqrt(n) = (z_a * sqrt(p0 * (1- p_0)) + z_b * sqrt(p_a * (1- p_a)))/(p_a - p_0)
n = ((z_a * sqrt(p_0 * (1- p_0)) + z_b * sqrt(p_a * (1- p_a)))/(p_a - p_0))^2
n
n/0.08
```

```{r}
# sample_size calculation 
p_0 = 0.53
p_a = p_0 - 0.01
#var_0 = p0 * (1- p_0) /n
#var_a = pa * (1- p_a) /n
alpha = 0.05
beta = 0.2

z_a = qnorm(1- alpha, lower.tail = T)
z_b = qnorm(1 - beta, lower.tail = T)

#((p_a) - (p_0 + z_a * sqrt(var_0)) )/ sqrt(var_a) = z_b

#p_a - p_0 = z_a * sqrt(var_0)) + z_b * sqrt(var_a))
#p_a - p_0 = z_a * sqrt(p_0 * (1- p_0) /n)) + z_b * sqrt(p_a * (1- p_a) /n))
#p_a - p_0 = z_a * sqrt(p_0 * (1- p_0) /n)) + z_b * sqrt(p_a * (1- p_a) /n))
#sqrt(n) = (z_a * sqrt(p0 * (1- p_0)) + z_b * sqrt(p_a * (1- p_a)))/(p_a - p_0)
n = ((z_a * sqrt(p_0 * (1- p_0)) + z_b * sqrt(p_a * (1- p_a)))/(p_a - p_0))^2
n
n/(660/40000)
```

```{r}
power.prop.test(p1 = 0.52, p2 = 0.53, sig.level = 0.05, power = 0.80, alternative = "two")
```

