---
title: "survival_power"
author: "Jerome"
date: "5/28/2020"
output: html_document
---

```{r}
library("powerSurvEpi")
```

# pilot data 
```{r}
# generate a toy pilot data set
set.seed(1)
X1 <- rnorm(100, mean = 0, sd = 0.3126)
X2 <- sample(c(0, 1), 100, replace = TRUE)
failureFlag <- sample(c(0, 1), 100, prob = c(0.25, 0.75), replace = TRUE)
dat <- data.frame(X1 = X1, X2 = X2, failureFlag = failureFlag)

# sample size 
ssizeEpiCont(formula = X1 ~ X2, dat = dat, X1 = X1, failureFlag = failureFlag,
power = 0.80, theta = exp(1), alpha = 0.05)
```

# default setting 
```{r}
# example in the EXAMPLE section (page 557) of Hsieh and Lavori (2000).
# Hsieh and Lavori (2000) assumed one-sided test,
# while this implementation assumed two-sided test.
# Hence alpha=0.1 here (two-sided test) will correspond
# to alpha=0.05 of one-sided test in Hsieh and Lavori's (2000) example.
ssizeEpiCont.default(power = 0.806, theta = exp(1), sigma2 = 0.3126^2,
psi = 0.738, rho2 = 0.1837, alpha = 0.1)
```

```{r}
ssizeEpiCont.default(power = 0.80, theta = exp(1), sigma2 = 0.3126^2,
psi = 0.3, rho2 = 0, alpha = 0.1)
```

```{r}
ss_cal <- function(hr) {
    sample_size <- ssizeEpiCont.default(power = 0.80, theta = hr , sigma2 = 0.3126^2,
psi = 0.3, rho2 = 0, alpha = 0.1)
    return(sample_size)

}
```

```{r}
hr_vec <- seq(0.8, 1.2, length.out = 100)
ss_vec <- sapply(hr_vec, ss_cal)
```

```{r}
plot(hr_vec, ss_vec)
lines(hr_vec, ss_vec)
```

```{r}
ss_cal <- function(hr) {
    sample_size <- ssizeEpiCont.default(power = 0.80, theta = hr , sigma2 = 0.3126^2,
psi = 0.3, rho2 = 0, alpha = 0.05)
    return(sample_size)

}

hr_vec <- seq(0.8, 1.2, length.out = 20)
ss_vec <- sapply(hr_vec, ss_cal)

plot(hr_vec, ss_vec)
lines(hr_vec, ss_vec)
```

```{r}
ss_cal <- function(hr) {
    sample_size <- ssizeEpiCont.default(power = 0.80, theta = hr , sigma2 = 0.3126^2,
psi = 0.3, rho2 = 0, alpha = 0.05)
    return(sample_size)

}

hr_vec <- seq(0.8, 1.2, length.out = 20)
ss_vec <- sapply(hr_vec, ss_cal)

plot(hr_vec, ss_vec)
lines(hr_vec, ss_vec)
```

```{r}
ss_cal <- function(hr) {
    sample_size <- ssizeEpiCont.default(power = 0.80, theta = hr , sigma2 = 0.3126^2,
psi = 0.3, rho2 = 0, alpha = 0.05)
    return(sample_size)

}

hr_vec <- seq(0.2, 5, length.out = 20)
ss_vec <- sapply(hr_vec, ss_cal)

plot(hr_vec, ss_vec)
lines(hr_vec, ss_vec)
ss_vec
```


```{r}
n1 = 167 - 61
n2 = 170 - 63
s1_2 = 114.7^2
s2_2 = 179.5^2

mean_diff = 12.89 - 11.79
df = (s1_2/n1 + s2_2/n2)
```

